In [1]:
import numpy as np

In [2]:
def compute_mean_and_variance(feature_vector):
    return np.mean(feature_vector), np.var(feature_vector)

In [3]:
N=5
feature_vector = np.random.rand(N)  
mean, variance = compute_mean_and_variance(feature_vector)
print("Feature vector:", feature_vector)
print("Mean:", mean)
print("Variance:", variance)

Feature vector: [0.53402525 0.6511331  0.54676731 0.87211563 0.45756932]
Mean: 0.6123221223254618
Variance: 0.020675044427109227


In [4]:
def compute_covariance(vector1, vector2):
    return np.cov(vector1, vector2)[0,1]
m=3
vector1 = np.random.rand(m)
vector2 = np.random.rand(m)
covariance = compute_covariance(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Covariance:", covariance)


Vector 1: [0.16469518 0.27433611 0.10499229]
Vector 2: [0.82913136 0.827213   0.12769893]
Covariance: 0.026687600618036968


In [5]:
def compute_correlation(vector1, vector2):
    return np.corrcoef(vector1, vector2)[0,1]
m=3
vector1 = np.random.rand(m)
vector2 = np.random.rand(m)
correlation = compute_correlation(vector1, vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Correlation:", correlation)

Vector 1: [0.99206895 0.68459212 0.68883632]
Vector 2: [0.88824607 0.40111965 0.3386556 ]
Correlation: 0.9932773090342693


In [6]:
def compute_correlation_matrix(feature_vector):
    correlation_matrix = np.corrcoef(feature_matrix)
  
    return correlation_matrix

In [7]:
feature_matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])


correlation_matrix = compute_correlation_matrix(feature_matrix)

In [8]:
print("\nCorrelation Matrix:")
print(correlation_matrix)


Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
